In [1]:

import pandas as pd
import sys
import os

sys.path.append("..")
from src.data_loader import DataLoader
from src.preprocess import Preprocessor

In [2]:
data_loader = DataLoader(path="../data/raw/order_return_data.csv")

In [3]:
data_loader.load()

Data yuklandi: 100000 qator, 14 ustun

,order_item_id,order_date,delivery_date,item_id,item_size,item_color,brand_id,item_price,user_id,user_title,user_dob,user_state,user_reg_date,return
0,1,2016-06-22,2016-06-27,643,38,navy,30,49.90,30822,Mrs,1969-04-17,Saxony,2016-06-23,0
1,2,2016-06-22,NaN,337,152,grey,30,19.95,30822,Mrs,1969-04-17,Saxony,2016-06-23,0
2,3,2016-06-22,2016-06-27,270,xxl,grey,49,79.90,30823,Mrs,1970-04-22,Baden-Wuerttemberg,2015-03-15,1
3,4,2016-06-22,2016-06-27,142,xxl,grey,49,99.90,30823,Mrs,1970-04-22,Baden-Wuerttemberg,2015-03-15,0
4,5,2016-06-22,2016-06-27,561,xxl,grey,3,14.90,30823,Mrs,1970-04-22,Baden-Wuerttemberg,2015-03-15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,2016-09-11,2016-09-12,156,20,blue,34,29.90,713,Mrs,1959-03-21,Rhineland-Palatinate,2015-02-17,0
99996,99997,2016-09-11,2016-09-12,156,20,brown,34,29.90,713,Mrs,1959-03-21,Rhineland-Palatinate,2015-02-17,0
99997,99998,2016-09-11,1994-12-31,1832,xxl,black,37,26.90,47794,Mr,1985-03-01,Hamburg,2016-09-10,0
99998,99999,2016-09-11,1994-12-31,1832,xxl,black,37,26.90,47794,Mr,1985-03-01,Hamburg,2016-09-10,0
99999,100000,2016-09-11,2016-10-08,1891,28,fuchsia,47,27.90,2622,Mrs,1973-10-17,Lower Saxony,2015-02-17,0

In [4]:
x_train, x_test, y_train, y_test = data_loader.split(target_column="return")

Train: 80000, Test: 20000

In [5]:
prep = Preprocessor()

In [6]:
x_train_filled, fill_values = prep.fillna_train(df=x_train)
x_test_filled = prep.fillna_test(df=x_test, fill_values=fill_values)

In [7]:
x_train_filled.info()

<class 'pandas.DataFrame'>
Index: 80000 entries, 75220 to 15795
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  80000 non-null  int64
 1   order_date     80000 non-null  str
 2   delivery_date  80000 non-null  str
 3   item_id        80000 non-null  int64
 4   item_size      80000 non-null  str
 5   item_color     80000 non-null  str
 6   brand_id       80000 non-null  int64
 7   item_price     80000 non-null  float64
 8   user_id        80000 non-null  int64
 9   user_title     80000 non-null  str
 10  user_dob       80000 non-null  str
 11  user_state     80000 non-null  str
 12  user_reg_date  80000 non-null  str
dtypes: float64(1), int64(4), str(8)
memory usage: 8.5 MB

In [8]:
x_train_encoded, encoders = prep.encode_train(df=x_train_filled)
x_test_encoded = prep.encode_test(
  df=x_test_filled, 
  encoders=encoders, 
  train_columns=x_train_encoded.columns
)

In [9]:
x_train_encoded.info()

<class 'pandas.DataFrame'>
Index: 80000 entries, 75220 to 15795
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  80000 non-null  int64
 1   order_date     80000 non-null  int64
 2   delivery_date  80000 non-null  int64
 3   item_id        80000 non-null  int64
 4   item_size      80000 non-null  int64
 5   item_color     80000 non-null  int64
 6   brand_id       80000 non-null  int64
 7   item_price     80000 non-null  float64
 8   user_id        80000 non-null  int64
 9   user_title     80000 non-null  int64
 10  user_dob       80000 non-null  int64
 11  user_state     80000 non-null  int64
 12  user_reg_date  80000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 8.5 MB

In [10]:
x_test_encoded.info()

<class 'pandas.DataFrame'>
Index: 20000 entries, 75721 to 42410
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  20000 non-null  int64
 1   order_date     20000 non-null  int64
 2   delivery_date  20000 non-null  int64
 3   item_id        20000 non-null  int64
 4   item_size      20000 non-null  int64
 5   item_color     20000 non-null  int64
 6   brand_id       20000 non-null  int64
 7   item_price     20000 non-null  float64
 8   user_id        20000 non-null  int64
 9   user_title     20000 non-null  int64
 10  user_dob       20000 non-null  int64
 11  user_state     20000 non-null  int64
 12  user_reg_date  20000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 2.1 MB

In [11]:
x_train_scaled, scalers = prep.scale_train(df=x_train_encoded)
x_test_scaled = prep.scale_test(df=x_test_encoded, scalers=scalers)

In [12]:
x_train_scaled

,order_item_id,order_date,delivery_date,item_id,item_size,item_color,brand_id,item_price,user_id,user_title,user_dob,user_state,user_reg_date
75220,0.872828,0.862590,0.559222,1.569487,-0.702821,0.382549,-1.033869,0.305712,1.187301,0.193858,1.384972,0.171045,-1.137186
48955,-0.036957,0.137221,-0.041402,0.826573,0.872707,0.382549,2.546649,-0.317006,0.127402,0.193858,0.965365,0.638453,0.462274
44966,-0.175131,-0.064270,-0.191558,0.856460,0.780029,-1.275924,0.632312,1.759756,0.025619,0.193858,-0.853730,-0.296363,-1.052060
13568,-1.262716,-1.232919,-1.042441,-1.106143,-0.517465,0.382549,-1.033869,-0.317006,-1.180691,0.193858,-1.567861,0.638453,-1.137186
92727,1.479247,1.467063,-0.992389,1.254958,0.872707,0.337725,2.830254,-1.001995,1.055979,0.193858,-0.621548,0.171045,0.619084
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6265,-1.515682,-1.313516,-1.142545,-0.697682,0.826368,1.144550,-0.076701,-0.109433,0.344919,0.193858,0.208474,0.171045,-1.137186
54886,0.168485,0.258116,0.058702,1.696152,0.362977,-0.917335,1.199523,0.515360,0.923020,0.193858,1.920071,-1.231178,-0.012635
76820,0.928250,0.902888,0.659326,1.616453,-0.239430,-0.738041,-1.033869,1.966291,1.206590,0.193858,0.260825,0.638453,0.529479
860,-1.702904,-1.434411,-1.192597,-1.313931,-0.610143,0.696314,-1.033869,1.136001,0.273101,0.193858,0.861862,-0.062659,1.067112
15795,-1.185575,-1.232919,-0.992389,-1.066293,0.733690,0.337725,-0.962968,-1.001995,0.240004,0.193858,-0.972819,-1.464882,-1.137186

In [13]:
x_test_scaled.info()

<class 'pandas.DataFrame'>
Index: 20000 entries, 75721 to 42410
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_item_id  20000 non-null  float64
 1   order_date     20000 non-null  float64
 2   delivery_date  20000 non-null  float64
 3   item_id        20000 non-null  float64
 4   item_size      20000 non-null  float64
 5   item_color     20000 non-null  float64
 6   brand_id       20000 non-null  float64
 7   item_price     20000 non-null  float64
 8   user_id        20000 non-null  float64
 9   user_title     20000 non-null  float64
 10  user_dob       20000 non-null  float64
 11  user_state     20000 non-null  float64
 12  user_reg_date  20000 non-null  float64
dtypes: float64(13)
memory usage: 2.1 MB

In [14]:
os.makedirs("../data/preprocessed", exist_ok=True)

x_train_scaled.to_csv("../data/preprocessed/x_train.csv", index=False)
x_test_scaled.to_csv("../data/preprocessed/x_test.csv",  index=False)
y_train.to_csv("../data/preprocessed/y_train.csv",  index=False)
y_test.to_csv("../data/preprocessed/y_test.csv",  index=False)